#DROP USER 'root'@'localhost';
CREATE USER 'root'@'localhost' IDENTIFIED BY 'scrat';
CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER ON test.* TO root@'localhost';
FLUSH PRIVILEGES;
USE root;
#DROP TABLE IF EXISTS users;
CREATE TABLE users(
id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
username VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户名',
password VARCHAR(50) NOT NULL DEFAULT '' COMMENT '密码',
status ENUM('1','0') NOT NULL DEFAULT '0' COMMENT '状态, 0 为普通用户, 1 为管理员',
INDEX(username),
PRIMARY KEY(id),
UNIQUE KEY(username)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT '用户帐号表';