#DROP USER 'root'@'localhost';
CREATE USER 'root'@'localhost' IDENTIFIED BY 'scrat';
CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER ON test.* TO root@'localhost';
FLUSH PRIVILEGES;
USE root;
#DROP TABLE IF EXISTS sample;
CREATE TABLE sample(
id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
PRIMARY KEY(id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT '样品';